### ISSUE TITLE
Need an example for new function"Fetch contacts in a contact list"

### ISSUE THREAD

**Issue by evgenybf** [Emarsys-US/Emarsys-postman-collection#2]
End-point "Get Contact Data in a Contact List" and some others have been recently marked as deprecated https://dev.emarsys.com/docs/core-api-reference/y5scc570znu3b-get-contact-data-in-a-contact-list

There are no working examples for the new end-point "Fetch contacts in a contact list ": 
https://dev.emarsys.com/docs/core-api-reference/20nck8oujcus8-fetch-contacts-in-a-contact-list

```
GET https://api.emarsys.net/api/v2/contactlist/{contactlistId}/contactIds
Accept: application/json
Content-Type: application/json
X-WSSE: UsernameToken Username="xxx", PasswordDigest=yyy", Nonce="zzz", Created="2024-03-22T16:11:24Z"

```

Tried to make it work with segment list scenario, but always get Error 403 (Forbidden).

Documentation doesn't help either. Mock server responds with 
```
"message": "Request path must have required property 'listid'"
```
whenever `contactlistId` is provided or not.

E.g. 
```
HTTP/1.1 422 Unprocessable Entity
Date: Fri, 22 Mar 2024 17:08:12 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 526
Connection: close
CF-Ray: 8687c848ded544bb-SIN
CF-Cache-Status: DYNAMIC
Via: 1.1 google
access-control-allow-headers: *
access-control-allow-methods: GET,POST,PUT,PATCH,DELETE,HEAD,OPTIONS,TRACE
alt-svc: h3=":443"; ma=86400
Vary: Accept-Encoding
Server: cloudflare

{
  "name": "https://stoplight.io/prism/errors#UNPROCESSABLE_ENTITY",
  "status": 422,
  "detail": "Your request is not valid and no HTTP validation response was found in the spec, so Prism is generating this error for you.",
  "additional": {
    "validation": [
      {
        "location": [
          "path"
        ],
        "severity": "Error",
        "code": "required",
        "message": "Request path must have required property 'listid'"
      }
    ],
    "workspaceSlug": "emarsys-sap",
    "projectSlug": "core-api-reference",
    "url": "/v2/contactlist/1/contactIds",
    "code": 200,
    "dynamic": true,
    "mediaTypes": [
      "application/json"
    ]
  }
}
```

Btw, sample request in documentation doesn't set listid in the path properly.  Here is an example (contactlistiId is not replaced with an id):
```
curl --request GET \
  --url https://api.emarsys.net/api/v2/contactlist/contactlistId/contactIds \
  --header 'Accept: application/json'
```

Old end-point works without issues
```
GET https://api.emarsys.net/api/v2/contactlist/{contactlistId}/contacts/data
Accept: application/json
Content-Type: application/json
X-WSSE: UsernameToken Username="xxx", PasswordDigest=yyy", Nonce="zzz", Created="2024-03-22T16:11:24Z"
```

it even works if the path is not complete (removed some characters at the end):
```
GET https://api.emarsys.net/api/v2/contactlist/{contactlistId}/contacts/dat
```
Then it responds with a list of ids.

**Comment by dwolter-emarsys** [comment]
Hi @evgenybf , Thanks for bringing this to my attention.

I just updated the endpoint in my collection - could you try it again now?

to answer some of your other notes:

- A 403 will usually either indicate an incorrect contact list ID (responded as a 403 to prevent scraping for contact lists) or that the API user needs additional permissions in your Emarsys account
- Endpoints that are deprecated but still working in the demo page is to be expected, at least until the endpoint is fully shutdown.

Best,
Dylan
